name: .NET Core

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core for building
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build with dotnet
        run: dotnet build --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core for testing
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Run test
        run: |
          cd ./LessPaper.WriteService.UnitTest
          dotnet test
